name: Docker

on:
  # Once a month
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - 'Dockerfile'
      - 'arm64.toolchain'
      - '.github/workflows/docker-image.yml'
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'Dockerfile'
      - 'arm64.toolchain'
      - '.github/workflows/docker-image.yml'
    branches:
      - '**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: douman/cross-flutter-pi4

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: douman
          ## Set in repo Settings->Secrets->New repository secret
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:latest
